/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AlertRecipients": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Alerts": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "Detections": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Detector": {
      "name": string
      "type": "sst.aws.Function"
    }
    "MediaBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "VideoIngest": {
      "arn": string
      "name": string
      "type": "aws.kinesis/videoStream.VideoStream"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}